---
config:
  layout: dagre
id: b6b09eb0-2153-43dd-880f-18d7bbcf5c0f
---
flowchart TD
    A["ISP Cloud"] -- WAN --> B("Cisco 2911 Router<br>Floor 1")
    B -- LAN --> C("Cisco 2960-24TT<br>Core Switch<br>Floor 1")
    C -- FA0/1 --> D("Cisco 2960-24TT<br>Switch<br>Floor 1") & E@{ label: "Cisco 2960-24TT<br style=\"--tw-scale-x:\">Switch 1<br>Floor 2" } & F@{ label: "Cisco 2960-24TT<br style=\"--tw-scale-x:\">Switch 2<br>Floor 3" }
    C -- "<span style=color:>FA0/1</span>" --> G("Cisco 2960-24TT<br>Switch 3<br>Floor 4")
    D -- FA0/4 --> n1["Access Point-PT<br>1st Floor AP"]
    D --> n5["PC 1"] & n7["PC 2"]
    E -- "<span style=color:>FA0/5</span>" --> n2@{ label: "Access Point-PT<br style=\"--tw-scale-x:\">2nd Floor AP" }
    E --> n6["PC3"] & n8["PC4"]
    E -- "<span style=color:>FA0/4</span>" --> n13["Server-PT"]
    F -- "<span style=color:>FA0/4</span>" --> n3@{ label: "Access Point-PT<br style=\"--tw-scale-x:\">3rd Floor AP" }
    F --> n9["PC5"] & n10["PC6"]
    G -- "<span style=color:>FA0/4</span>" --> n4["Access Point-PT<br>4th Floor AP"]
    G --> n11["PC7"] & n12["PC8"]
    n14["DHCP Server"] --> C
    E@{ shape: rounded}
    F@{ shape: rounded}
    n2@{ shape: rect}
    n3@{ shape: rect}